name: my_pick
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  go_router: ^15.1.1
  flutter_svg: ^2.1.0
  async: ^2.12.0
  collection: ^1.19.1
  flutter_dotenv: ^5.2.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  firebase_messaging: ^15.0.4
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1
  firebase_crashlytics: ^4.0.4
  cloud_firestore: ^5.2.1
  dio: ^5.6.0
  retrofit: ^4.2.0
  shared_preferences: ^2.3.2
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.21.2
  riverpod_annotation: ^2.3.5
  gap: ^3.0.1
  flutter_animate: ^4.5.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.15
  go_router_builder: ^2.8.2
  riverpod_generator: ^2.3.3
  custom_lint: ^0.7.0
  riverpod_lint: ^2.3.13
  freezed: ^3.0.6
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.9

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/splash/

flutter_assets_generator:
  # Optional. Sets the directory of generated localization files. Provided value should be a valid path on lib dir. Default: generated
  output_dir: core/constants
  # Optional. Sets whether utomatic monitoring of file changes. Default: true
  auto_detection: true
  # Optional. Sets file name conversion rules. Default: true
  named_with_parent: true
  # Optional. Sets the name for the generated localization file. Default: assets
  output_filename: assets
  # Optional. Sets the name for the generated localization class. Default: Assets
  class_name: Assets
  # Optional. Sets the filename split pattern for filename split. Default: [-_]
  filename_split_pattern: "[-_ ]"
  # Optional. Configuring ignore paths. Default: [],e.g: ["assets/fonts", "assets/images/dark", ...]
  path_ignore:
    [ "env", "assets/l10n" ]

#flutter_intl:
#  enabled: true # Required. Must be set to true to activate the plugin. Default: false
#  class_name: AppIntl # Optional. Sets the name for the generated localization class. Default: S
#  main_locale: en_US # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
#  arb_dir: assets/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
#  output_dir: lib/core/translation # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
#  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false
